// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: creators.proto

package creatorspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MostActiveCreatorsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creators []*Creator `protobuf:"bytes,1,rep,name=creators,proto3" json:"creators,omitempty"`
	Products []*Product `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *MostActiveCreatorsReq) Reset() {
	*x = MostActiveCreatorsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_creators_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MostActiveCreatorsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MostActiveCreatorsReq) ProtoMessage() {}

func (x *MostActiveCreatorsReq) ProtoReflect() protoreflect.Message {
	mi := &file_creators_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MostActiveCreatorsReq.ProtoReflect.Descriptor instead.
func (*MostActiveCreatorsReq) Descriptor() ([]byte, []int) {
	return file_creators_proto_rawDescGZIP(), []int{0}
}

func (x *MostActiveCreatorsReq) GetCreators() []*Creator {
	if x != nil {
		return x.Creators
	}
	return nil
}

func (x *MostActiveCreatorsReq) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type MostActiveCreatorsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List is ordered by activity with the most active creator first.
	CreatorStats []*CreatorStats `protobuf:"bytes,1,rep,name=creatorStats,proto3" json:"creatorStats,omitempty"`
}

func (x *MostActiveCreatorsRes) Reset() {
	*x = MostActiveCreatorsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_creators_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MostActiveCreatorsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MostActiveCreatorsRes) ProtoMessage() {}

func (x *MostActiveCreatorsRes) ProtoReflect() protoreflect.Message {
	mi := &file_creators_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MostActiveCreatorsRes.ProtoReflect.Descriptor instead.
func (*MostActiveCreatorsRes) Descriptor() ([]byte, []int) {
	return file_creators_proto_rawDescGZIP(), []int{1}
}

func (x *MostActiveCreatorsRes) GetCreatorStats() []*CreatorStats {
	if x != nil {
		return x.CreatorStats
	}
	return nil
}

type Creator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *Creator) Reset() {
	*x = Creator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_creators_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Creator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Creator) ProtoMessage() {}

func (x *Creator) ProtoReflect() protoreflect.Message {
	mi := &file_creators_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Creator.ProtoReflect.Descriptor instead.
func (*Creator) Descriptor() ([]byte, []int) {
	return file_creators_proto_rawDescGZIP(), []int{2}
}

func (x *Creator) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Creator) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId  string                 `protobuf:"bytes,2,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
}

func (x *Product) Reset() {
	*x = Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_creators_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_creators_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_creators_proto_rawDescGZIP(), []int{3}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Product) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type CreatorStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creator *Creator `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// The number of products created by this creator
	ProductCount int32 `protobuf:"varint,2,opt,name=productCount,proto3" json:"productCount,omitempty"`
	// The createTime of the product this creator most recently created.
	MostRecentCreateTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=mostRecentCreateTime,proto3" json:"mostRecentCreateTime,omitempty"`
}

func (x *CreatorStats) Reset() {
	*x = CreatorStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_creators_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatorStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatorStats) ProtoMessage() {}

func (x *CreatorStats) ProtoReflect() protoreflect.Message {
	mi := &file_creators_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatorStats.ProtoReflect.Descriptor instead.
func (*CreatorStats) Descriptor() ([]byte, []int) {
	return file_creators_proto_rawDescGZIP(), []int{4}
}

func (x *CreatorStats) GetCreator() *Creator {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *CreatorStats) GetProductCount() int32 {
	if x != nil {
		return x.ProductCount
	}
	return 0
}

func (x *CreatorStats) GetMostRecentCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.MostRecentCreateTime
	}
	return nil
}

var File_creators_proto protoreflect.FileDescriptor

var file_creators_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79, 0x0a,
	0x15, 0x4d, 0x6f, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x2f, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x6f, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x22, 0x55, 0x0a, 0x15, 0x4d, 0x6f, 0x73, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x12, 0x3c, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x73, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x22,
	0x2f, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x22, 0x73, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xb1, 0x01, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x73, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x07, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x4e, 0x0a, 0x14, 0x6d, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x14, 0x6d, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x32, 0x68, 0x0a, 0x08, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x5c, 0x0a, 0x12, 0x4d, 0x6f, 0x73, 0x74, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x21, 0x2e, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x73, 0x74, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x21,
	0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x73, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x52, 0x65, 0x6c, 0x6c, 0x75, 0x6d, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x69,
	0x76, 0x65, 0x5f, 0x77, 0x65, 0x61, 0x76, 0x65, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_creators_proto_rawDescOnce sync.Once
	file_creators_proto_rawDescData = file_creators_proto_rawDesc
)

func file_creators_proto_rawDescGZIP() []byte {
	file_creators_proto_rawDescOnce.Do(func() {
		file_creators_proto_rawDescData = protoimpl.X.CompressGZIP(file_creators_proto_rawDescData)
	})
	return file_creators_proto_rawDescData
}

var file_creators_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_creators_proto_goTypes = []any{
	(*MostActiveCreatorsReq)(nil), // 0: creatorspb.MostActiveCreatorsReq
	(*MostActiveCreatorsRes)(nil), // 1: creatorspb.MostActiveCreatorsRes
	(*Creator)(nil),               // 2: creatorspb.Creator
	(*Product)(nil),               // 3: creatorspb.Product
	(*CreatorStats)(nil),          // 4: creatorspb.CreatorStats
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_creators_proto_depIdxs = []int32{
	2, // 0: creatorspb.MostActiveCreatorsReq.creators:type_name -> creatorspb.Creator
	3, // 1: creatorspb.MostActiveCreatorsReq.products:type_name -> creatorspb.Product
	4, // 2: creatorspb.MostActiveCreatorsRes.creatorStats:type_name -> creatorspb.CreatorStats
	5, // 3: creatorspb.Product.createTime:type_name -> google.protobuf.Timestamp
	2, // 4: creatorspb.CreatorStats.creator:type_name -> creatorspb.Creator
	5, // 5: creatorspb.CreatorStats.mostRecentCreateTime:type_name -> google.protobuf.Timestamp
	0, // 6: creatorspb.Creators.MostActiveCreators:input_type -> creatorspb.MostActiveCreatorsReq
	1, // 7: creatorspb.Creators.MostActiveCreators:output_type -> creatorspb.MostActiveCreatorsRes
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_creators_proto_init() }
func file_creators_proto_init() {
	if File_creators_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_creators_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MostActiveCreatorsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_creators_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MostActiveCreatorsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_creators_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Creator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_creators_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_creators_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreatorStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_creators_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_creators_proto_goTypes,
		DependencyIndexes: file_creators_proto_depIdxs,
		MessageInfos:      file_creators_proto_msgTypes,
	}.Build()
	File_creators_proto = out.File
	file_creators_proto_rawDesc = nil
	file_creators_proto_goTypes = nil
	file_creators_proto_depIdxs = nil
}
